### ISSUE TITLE
Input files for running STRIDE

### ISSUE THREAD

**Issue by julie-jch** [DongqingSun96/STRIDE#4]
Hello, I found your paper online and thought this tool was interesting and wanted to give it a try.
Is there information on the input files/ generation of the necessary files needed to run STRIDE? If so, where can I find that information?
Thank you in advance.

**Comment by DongqingSun96** [comment]
Hi, thanks for your interest. Please refer to the [documentation](https://stridespatial.readthedocs.io/en/latest/) for full usage of STRIDE.

**Comment by julie-jch** [comment]
Thank you for your response. To followup, the spot location input file, how was that generated? I have a spot bar-code csv from space ranger, but this isn't required. I apologize if the answer to this question is obvious.

**Comment by DongqingSun96** [comment]
HI, sorry for the late response. Space ranger provides a barcode-location file named as `tissue_positions_list.csv`, which can be modified to the input file for STRIDE. By the way, the barcode location file is not necessary to perform deconvolution, and it's only required when visualizing the result.
