### ISSUE TITLE
How to increase the number of passes or iterations to improve accuracy

### ISSUE THREAD

**Issue by PSSUN** [DongqingSun96/STRIDE#8]
Hi,

When I try to run fellow demo https://stridespatial.readthedocs.io/en/latest/tutorials/Human_heart.html

In **Step 1 Deconvolve the cell-type composition of ST data**, I used command as the demo:
`STRIDE deconvolve --sc-count Data/Human_heart_scRNA_gene_count.h5 \
--sc-celltype Data/Human_heart_scRNA_celltype_curated.txt \
--gene-use Data/Human_heart_scRNA_markers.txt \
--st-count Data/Human_heart_ST_gene_count.h5 \
--outdir Result/STRIDE --outprefix Human_heart --normalize`

I used data in STRIDE/test, and I can see the such output in the terminal:
> Reading spatial count matrix...
Reading single-cell count matrix...
Training topic model...
Selecting the optimal model.
Number of topics: 11
WARNING: too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
Number of topics: 12
WARNING: too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
Number of topics: 13
WARNING: too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
Number of topics: 14
WARNING: too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy

When I run `STRIDE deconvolve --help`, I didn't find any parameters to increase the number of passes or iterations. Is there anything I missed? Please let me know, thx!

**Comment by DongqingSun96** [comment]
Hi, sorry for the late response! These warnings don't affect the deconvolution results. Please ignore them. In the next version, we will increase the number of iterations by default to avoid these warnings. Thanks!

**Comment by PSSUN** [comment]
Thanks
